version: 2
jobs:
  build:
    machine: true
    steps: 
      - checkout
      - run: docker build .
  test:
    machine: true
    steps:
      - checkout
      - run: docker-compose up -f BTCPayServer.Tests/docker-compose.yml tests


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
