version: 2
jobs:
  build:
    machine: true
    steps: 
      - checkout
      - run: docker build .
  test:
    machine: true
    steps:
      - run: lsb_release -a
      - checkout
      - run: wget -q https://packages.microsoft.com/config/ubuntu/14.04/packages-microsoft-prod.deb
      - run: sudo dpkg -i packages-microsoft-prod.deb
      - run: sudo apt-get install apt-transport-https
      - run: sudo apt-get update
      - run: sudo apt-get install dotnet-sdk-2.1
 
      - run: cd BTCPayServer.Tests && docker-compose up -d && dotnet test


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
