version: 2
jobs:
  build:
    working_directory: ~/btcpayserver
    machine: true
    steps: 
      - run: docker build .
  test:
    working_directory: ~/btcpayserver
    machine: true
    steps:
      - run: cd BTCPayServer.Tests 
      - run: docker-compose up tests


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
